quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_app.urls')),
]

quotes/quotes_app/urls.py
from django.urls import path
from . import views

app_name = 'quotes_app'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('author/<str:fullname>/', views.author_detail, name='author_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

quotes/quotes_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Quote(models.Model):
    quote = models.TextField()
    author = models.TextField()
    tags = models.TextField()

    def __str__(self):
        return self.quote


class Author(models.Model):
    fullname = models.TextField()
    born_date = models.DateField()
    born_location = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.fullname


class User(AbstractUser):
    username = models.CharField(unique=True)

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        related_name='custom_user_set',
        related_query_name='custom_user',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name='custom_user_set',
        related_query_name='custom_user',
    )

    def __str__(self):
        return self.username

quotes/quotes_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Author, Quote, User


class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    born_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    born_location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    quote = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    author = forms.ModelChoiceField(queryset=Author.objects.all())
    tags = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']


class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quotes_app/views.py
from django.contrib.auth import authenticate, logout, login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import QuoteForm, AuthorForm, RegisterForm, LoginForm
from .models import Quote, Author, User


def main(request):
    quotes = Quote.objects.all()
    context = {'quotes': quotes}
    return render(request, 'base.html', context)


def quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_app:main')
        else:
            return render(request, 'quote.html', {'form': form})

    return render(request, 'quote.html', {'form': QuoteForm()})


def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_app:main')
        else:
            return render(request, 'author.html', {'form': form})

    return render(request, 'author.html', {'form': AuthorForm()})


def author_detail(request, fullname):
    quotes_by_author = Quote.objects.filter(author=fullname)

    author = Author.objects.get(fullname=fullname)

    context = {'author': author, 'quotes_by_author': quotes_by_author}
    return render(request, 'author_detail.html', context)


def register(request):
    if request.user.is_authenticated:
        return redirect(to='quotes_app:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_app:main')
        else:
            return render(request, 'register.html', context={"form": form})

    return render(request, 'register.html', context={"form": RegisterForm()})


def user_login(request):
    if request.user.is_authenticated:
        return redirect(to='quotes_app:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='quotes_app:login')

        login(request, user)
        return redirect(to='quotes_app:main')

    return render(request, 'login.html', context={"form": LoginForm()})


@login_required
def user_logout(request):
    logout(request)
    return redirect(to='quotes_app:main')

quotes/quotes_app/templates/author.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action="{% url 'quotes_app:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the full name:
            {{form.fullname}}
        </label>
        <label>Enter the born date:
            {{form.born_date}}
        </label>
        <label>Enter the born location:
            {{form.born_location}}
        </label>
        <label>Enter the description:
            {{form.description}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotes_app/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ author.fullname }}</h1>
    <p>Born: {{ author.born_date }} in {{ author.born_location }}</p>
    <p>Description: {{ author.description }}</p>

    <h2>Quotes</h2>
        {% for quote in quotes_by_author %}
            <article>{{ quote.quote }}<br>
            {% load functions %}
            {% for tag in quote.tags|split_str:", " %}
                <a href="#">{{ tag }}</a>
            {% endfor %}
            </article>
        {% endfor %}
{% endblock %}

quotes/quotes_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="/author/" role="button"> Add author </a></li>
        </ul>
        <ul>
            <li><a href="/quote/" role="button"> Add quote </a></li>
        </ul>
        <ul>
            <li><a href="/logout/" role="button"> Logout </a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="/login/" role="button"> Login </a></li>
        </ul>
        <ul>
            <li><a href="/register/" role="button"> Register </a></li>
        </ul>
        {% endif %}
    </nav>
    {% block content %}
        {% for quote in quotes %}
        <div class="quote-block">
            <article>
                <a href="{% url 'quotes_app:author_detail' quote.author %}">{{ quote.author }}</a>
                {% with tags=quote.tags %}
                <p>{{ quote.quote }}</p>
                    {% load functions %}
                    {% for tag in tags|split_str:", " %}
                    <a href="#">{{ tag }}</a>
                    {% endfor %}
                {% endwith %}
            </article>
        </div>
        {% endfor %}
    {% endblock %}
</main>
</body>
</html>

quotes/quotes_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>Main page</h1>
</main>
</body>
</html>

quotes/quotes_app/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'quotes_app:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotes_app/templates/quote.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_app:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote:
            {{form.quote}}
        </label>
        <label>Enter the author:
            {{form.author}}
        </label>
        <label>Enter the tags:
            {{form.tags}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotes_app/templates/register.html
{% extends "base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'quotes_app:register' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}